const services = [
  {
    key: 101,
    status: "Basic",
    title: "Drawing Lessons",
    img: "https://i.postimg.cc/GtVGmcSB/service-1.jpg",
    Students: 14973,
    Time: "2h 46m",
    price: 20,
    Instructor: "Joseph Morgan",
    description:
      "basic drawing lesson for children , help finding their own style.",
  },
  {
    key: 102,
    status: "Basic",
    title: "Painting Lessons",
    img: "https://i.postimg.cc/V66TT7rZ/181632.jpg",
    Students: 12973,
    Time: "2h 46m",
    price: 20,
    Instructor: "Andira Winter",
    description:
      "painting from the very basic as per student need from basic to advance",
  },
  {
    key: 103,
    status: "Basic",
    title: "Mixed Lessons",
    img: "https://i.postimg.cc/yN9DFMYR/sijmen-van-hooff-E0y-S34z-GQRY-unsplash.jpg",
    Students: 14973,
    Time: "2h 46m",
    price: 24,
    Instructor: "Alexa Rox",
    description:
      "combining previous and new skills to implement things creatively",
  },
  {
    key: 104,
    status: "Advance",
    title: "Illustration",
    img: "https://i.postimg.cc/Sxkx3gq0/istockphoto-521577939-170667a.jpg",
    Students: 12953,
    Time: "3h 46m",
    price: 30,
    Instructor: "Monica Geller",
    description:
      "illustration lesson which provide student with new perspective learning new skill",
  },
  {
    key: 105,
    status: "Advance",
    title: "Form & Space",
    img: "https://i.postimg.cc/HnRP58Ld/dhanya-a-v-zdi-MKVb5fl0-unsplash.jpg",
    Time: "3h 46m",
    price: 32,
    Students: 11963,
    Instructor: "Taylor Smith",
    description: "Form and Space 3D drawing and Perspective",
  },
  {
    key: 106,
    status: "Advance",
    title: "Measuring & Precison",
    img: "https://i.postimg.cc/QMFhZ1WJ/daniel-mccullough-Ht-Bl-Qdxf-G9k-unsplash.jpg",
    Time: "4h 16m",
    Students: 1963,
    Instructor: "Andre ken",
    description: "Measuring and Proportion with accuracy and precision",
    price: 34,
  },
  {
    key: 107,
    status: "Advance",
    title: "Shading Lessons",
    img: "https://i.postimg.cc/YSTLm1cd/istockphoto-1042016616-170667a.jpg",
    Time: "4h 16m",
    price: 35,
    Students: 1563,
    Instructor: "Ross Geller",
    description:
      "creative way in shading starting with the basics and with new skills",
  },
  {
    key: 108,
    status: "Advance",
    title: "Dynamic Making",
    img: "https://i.postimg.cc/wvbfN4qS/felipepelaquim-Mu-Gk-Tlj-lg-unsplash.jpg",
    Time: "6h 16m",
    price: 36,
    Students: 1563,
    Instructor: "karen Smith",
    description: "advance dynamic drawing, providing the tools technique ",
  },
  {
    key: 109,
    status: "Advance",
    title: "Expression & Creativity",
    img: "https://i.postimg.cc/HsMMd8bH/birmingham-museums-trust-HEEv-Yh-Nzp-Eo-unsplash.jpg",
    Time: "8h 16m",
    price: 37,
    Instructor: "Rachel Green",
    description: "drawing with expression, creativity and liveliness",
  },
];
